// <auto-generated />
namespace CreativeWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrationDataAnnot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationDataAnnot));
        
        string IMigrationMetadata.Id
        {
            get { return "201607111537483_migrationDataAnnot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
